name: doancuoiky_test2
description: "Chatbot hỗ trợ tâm lý AI"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^10.0.0
  intl: ^0.20.2
  file_picker: ^10.3.8
  provider: ^6.1.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  google_generative_ai: ^0.4.7
  firebase_core: ^3.4.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  flutter_markdown: ^0.7.0
  share_plus: ^12.0.1
  fl_chart: ^0.66.0
  local_auth: ^2.1.6
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
